// AUTO-GENERATED by scripts/gen_offsets.mjs — DO NOT EDIT.
// Rerun `node scripts/gen_offsets.mjs` to refresh.
// Last refresh: 2026-07-22T21:35:11.132Z
// Build id:     14
// Game version: 41.20 (12:19 pm (EST))

#pragma once
#include <cstdint>

namespace off {

    inline constexpr const char* build_version = "41.20";
    inline constexpr const char* build_label   = "12:19 pm (EST)";
    inline constexpr std::uint64_t build_id    = 14ULL;

    namespace a_actor {
        inline constexpr std::uintptr_t bAllowTickBeforeBeginPlay = 0x5A;
        inline constexpr std::uintptr_t bAlwaysRelevant = 0x58;
        inline constexpr std::uintptr_t bAutoDestroyWhenFinished = 0x5A;
        inline constexpr std::uintptr_t bBlockInput = 0x5A;
        inline constexpr std::uintptr_t bCallPreReplication = 0x58;
        inline constexpr std::uintptr_t bCallPreReplicationForReplay = 0x58;
        inline constexpr std::uintptr_t bCanBeDamaged = 0x5A;
        inline constexpr std::uintptr_t bExchangedRoles = 0x59;
        inline constexpr std::uintptr_t bForceNetAddressable = 0x59;
        inline constexpr std::uintptr_t bHidden = 0x58;
        inline constexpr std::uintptr_t bNetLoadOnClient = 0x59;
        inline constexpr std::uintptr_t bNetTemporary = 0x58;
        inline constexpr std::uintptr_t bNetUseOwnerRelevancy = 0x59;
        inline constexpr std::uintptr_t bOnlyRelevantToOwner = 0x58;
        inline constexpr std::uintptr_t bRelevantForLevelBounds = 0x59;
        inline constexpr std::uintptr_t bRelevantForNetworkReplays = 0x59;
        inline constexpr std::uintptr_t bReplayRewindable = 0x59;
        inline constexpr std::uintptr_t bReplicateMovement = 0x58;
        inline constexpr std::uintptr_t bTearOff = 0x59;
        inline constexpr std::uintptr_t PrimaryActorTick = 0x28;
    }

    namespace a_building_actor {
        inline constexpr std::uintptr_t AbilitySystemComponent = 0x408;
        inline constexpr std::uintptr_t AreaClass = 0x380;
        inline constexpr std::uintptr_t BuildingAttributeSet = 0x3D0;
        inline constexpr std::uintptr_t BuildingAttributeSetClass = 0x3C8;
        inline constexpr std::uintptr_t CurrentBuildingLevel = 0x3C0;
        inline constexpr std::uintptr_t DamageAttributeSet = 0x3D8;
        inline constexpr std::uintptr_t DynamicBuildingPlacementType = 0x432;
        inline constexpr std::uintptr_t ForceMetadataRelevant = 0x430;
        inline constexpr std::uintptr_t HealthBarIndicator = 0x428;
        inline constexpr std::uintptr_t HealthBarIndicatorDifficultyRating = 0x3C4;
        inline constexpr std::uintptr_t InitialOverlappingVehicles = 0x3B0;
        inline constexpr std::uintptr_t LastMetadataRelevant = 0x431;
        inline constexpr std::uintptr_t MyGuid = 0x368;
        inline constexpr std::uintptr_t NavigationObstacleOverride = 0x433;
        inline constexpr std::uintptr_t OnAbilitySystemComponentInitialized = 0x3F8;
        inline constexpr std::uintptr_t OwnerPersistentID = 0x37C;
        inline constexpr std::uintptr_t PendingDamageImpactCues = 0x418;
        inline constexpr std::uintptr_t ReplicatedAbilitySystemComponent = 0x410;
        inline constexpr std::uintptr_t ReplicatedBuildingAttributeSet = 0x3E0;
        inline constexpr std::uintptr_t SavedHealthPct = 0x378;
    }

    namespace a_building_container {
        inline constexpr std::uintptr_t AdditionalPickupTags = 0xB58;
        inline constexpr std::uintptr_t ChosenRandomUpgrade = 0xBC4;
        inline constexpr std::uintptr_t ContainerLootTierKey = 0xBA4;
        inline constexpr std::uintptr_t LootRepeatSoundCue = 0xB38;
        inline constexpr std::uintptr_t LootTierGroupTagOverrideData = 0xB90;
        inline constexpr std::uintptr_t MarkerDisplay = 0xBC8;
        inline constexpr std::uintptr_t MarkerPositionOffset = 0xC78;
        inline constexpr std::uintptr_t NumItemsToDropRange = 0xC84;
        inline constexpr std::uintptr_t OnContainerRandomUpgradeApplied = 0xB20;
        inline constexpr std::uintptr_t OnContainerSearchedStateChangedClient = 0xB10;
        inline constexpr std::uintptr_t OnDamageSoundCue = 0xB40;
        inline constexpr std::uintptr_t OnDeathSoundCue = 0xB48;
        inline constexpr std::uintptr_t PotentialRandomUpgrades = 0xBA8;
        inline constexpr std::uintptr_t ReplicatedLootTier = 0xBC0;
        inline constexpr std::uintptr_t SearchedMaterialOverrides = 0xB80;
        inline constexpr std::uintptr_t SearchedMesh = 0xB50;
        inline constexpr std::uintptr_t SearchingSoundCueLoop = 0xB30;
        inline constexpr std::uintptr_t SearchLootTierChosenQuotaInfo = 0xBB8;
        inline constexpr std::uintptr_t SearchLootTierGroup = 0xBA0;
        inline constexpr std::uintptr_t SpawnSourceOverride = 0xB78;
    }

    namespace a_building_gameplay_actor {
        inline constexpr std::uintptr_t AbilitySourceLevel = 0x76C;
        inline constexpr std::uintptr_t bAddOwnerVelocity = 0x769;
        inline constexpr std::uintptr_t bAllowRidingOnActor = 0x700;
        inline constexpr std::uintptr_t bApplyDefaultEnabledAbilityBucketsOnInit = 0x810;
        inline constexpr std::uintptr_t bBlockMarking = 0x810;
        inline constexpr std::uintptr_t bCanBeMarked = 0x810;
        inline constexpr std::uintptr_t bIgnoreInstigatorCollision = 0x768;
        inline constexpr std::uintptr_t bShowInteractKeybind = 0x810;
        inline constexpr std::uintptr_t bUseSimpleActorTouchSetupForAbilityBuckets = 0x810;
        inline constexpr std::uintptr_t DamageStatHandle = 0x6F0;
        inline constexpr std::uintptr_t DeliverableAbilityInfo = 0x770;
        inline constexpr std::uintptr_t InherentAbilitySets = 0x6C8;
        inline constexpr std::uintptr_t MarkerDisplay = 0x818;
        inline constexpr std::uintptr_t MarkerPositionOffset = 0x8C8;
        inline constexpr std::uintptr_t OnDeliverableAbilityInfoAppliedToTouchingActor = 0x738;
        inline constexpr std::uintptr_t OnDeliverableAbilityInfoChangedForExitingTouchActor = 0x748;
        inline constexpr std::uintptr_t OnDidDamage = 0x758;
        inline constexpr std::uintptr_t OnProximityEffectsAppliedDelegate = 0x728;
        inline constexpr std::uintptr_t OnProximityPrePulseDelegate = 0x718;
        inline constexpr std::uintptr_t OnProximityPulseDelegate = 0x708;
    }

    namespace a_building_prop {
        inline constexpr std::uintptr_t bBlockMarking = 0xB10;
        inline constexpr std::uintptr_t bCanBeMarked = 0xB10;
        inline constexpr std::uintptr_t bDoNotBlockMarkerTraceWhenOverlappingPlayer = 0xB10;
        inline constexpr std::uintptr_t bIsBuildingVolume = 0xB10;
        inline constexpr std::uintptr_t bListensForInitQuests_Complete = 0xB10;
        inline constexpr std::uintptr_t bSuppressSimpleInteractionWidgetForTouch = 0xB10;
        inline constexpr std::uintptr_t bUseDamageSet = 0xB10;
    }

    namespace a_building_sm_actor {
        inline constexpr std::uintptr_t AltMeshIdx = 0x704;
        inline constexpr std::uintptr_t bAllowBuildingCheat = 0x708;
        inline constexpr std::uintptr_t bAttachmentPlacementBlockedBack = 0x708;
        inline constexpr std::uintptr_t bAttachmentPlacementBlockedFront = 0x708;
        inline constexpr std::uintptr_t bCameraOnlyCollision = 0x709;
        inline constexpr std::uintptr_t bForceReplicateSubObjects = 0x700;
        inline constexpr std::uintptr_t bHiddenDueToTrapPlacement = 0x708;
        inline constexpr std::uintptr_t bMirrored = 0x708;
        inline constexpr std::uintptr_t bNoCameraCollision = 0x700;
        inline constexpr std::uintptr_t bNoCollision = 0x708;
        inline constexpr std::uintptr_t bNoPawnCollision = 0x700;
        inline constexpr std::uintptr_t bNoPhysicsCollision = 0x700;
        inline constexpr std::uintptr_t bNoVisibilityCollision = 0x708;
        inline constexpr std::uintptr_t bSupportsRepairing = 0x708;
        inline constexpr std::uintptr_t bUseSingleMeshCullDistance = 0x700;
        inline constexpr std::uintptr_t CurAnimSubObjectNum = 0x702;
        inline constexpr std::uintptr_t CurAnimSubObjectTargetNum = 0x703;
        inline constexpr std::uintptr_t ResourceType = 0x701;
        inline constexpr std::uintptr_t StaticMesh = 0x6F8;
        inline constexpr std::uintptr_t TextureData = 0x6D8;
    }

    namespace a_building_weak_spot {
        inline constexpr std::uintptr_t bActive = 0x2A0;
        inline constexpr std::uintptr_t bFadeOut = 0x2A0;
        inline constexpr std::uintptr_t bHit = 0x2A0;
        inline constexpr std::uintptr_t HitCount = 0x2A4;
        inline constexpr std::uintptr_t HitNormal = 0x2C8;
        inline constexpr std::uintptr_t Level = 0x2A8;
        inline constexpr std::uintptr_t MaxLevel = 0x2AC;
        inline constexpr std::uintptr_t ParentObject = 0x298;
        inline constexpr std::uintptr_t PhysicalSurfaceType = 0x2E0;
        inline constexpr std::uintptr_t StartingLocation = 0x2B0;
    }

    namespace a_camera_actor {
        inline constexpr std::uintptr_t AspectRatio = 0x28C;
        inline constexpr std::uintptr_t AutoActivateForPlayer = 0x270;
        inline constexpr std::uintptr_t bConstrainAspectRatio = 0x288;
        inline constexpr std::uintptr_t CameraComponent = 0x278;
        inline constexpr std::uintptr_t FOVAngle = 0x290;
        inline constexpr std::uintptr_t PostProcessBlendWeight = 0x294;
        inline constexpr std::uintptr_t PostProcessSettings = 0x2A0;
        inline constexpr std::uintptr_t SceneComponent = 0x280;
    }

    namespace a_character {
        inline constexpr std::uintptr_t AnimRootMotionTranslationScale = 0x428;
        inline constexpr std::uintptr_t BasedMovement = 0x308;
        inline constexpr std::uintptr_t BaseRotationOffset = 0x3C0;
        inline constexpr std::uintptr_t BaseTranslationOffset = 0x3E0;
        inline constexpr std::uintptr_t bClientResimulateRootMotion = 0x430;
        inline constexpr std::uintptr_t bClientResimulateRootMotionSources = 0x430;
        inline constexpr std::uintptr_t bClientUpdating = 0x430;
        inline constexpr std::uintptr_t bClientWasFalling = 0x430;
        inline constexpr std::uintptr_t bInBaseReplication = 0x430;
        inline constexpr std::uintptr_t bIsCrouched = 0x430;
        inline constexpr std::uintptr_t bPressedJump = 0x430;
        inline constexpr std::uintptr_t bProxyIsJumpForceApplied = 0x430;
        inline constexpr std::uintptr_t CapsuleComponent = 0x300;
        inline constexpr std::uintptr_t CharacterMovement = 0x2F8;
        inline constexpr std::uintptr_t CrouchedEyeHeight = 0x42C;
        inline constexpr std::uintptr_t Mesh = 0x2F0;
        inline constexpr std::uintptr_t ReplayLastTransformUpdateTimeStamp = 0x3BC;
        inline constexpr std::uintptr_t ReplicatedBasedMovement = 0x360;
        inline constexpr std::uintptr_t ReplicatedGravityDirection = 0x3F8;
        inline constexpr std::uintptr_t ReplicatedServerLastTransformUpdateTimeStamp = 0x3B8;
    }

    namespace a_controller {
        inline constexpr std::uintptr_t bAttachToPawn = 0x300;
        inline constexpr std::uintptr_t Character = 0x2C0;
        inline constexpr std::uintptr_t ControlRotation = 0x2E8;
        inline constexpr std::uintptr_t OnInstigatedAnyDamage = 0x288;
        inline constexpr std::uintptr_t OnPossessedPawnChanged = 0x298;
        inline constexpr std::uintptr_t Pawn = 0x2B0;
        inline constexpr std::uintptr_t PlayerState = 0x278;
        inline constexpr std::uintptr_t StateName = 0x2A8;
        inline constexpr std::uintptr_t TransformComponent = 0x2C8;
    }

    namespace a_fort_ai_pawn {
        inline constexpr std::uintptr_t AnimationSharingSetup = 0x22B8;
        inline constexpr std::uintptr_t AttributeReplicationProxy = 0x1F90;
        inline constexpr std::uintptr_t bAnimateOnServer = 0x22D8;
        inline constexpr std::uintptr_t bAttacking = 0x22B0;
        inline constexpr std::uintptr_t bDancing = 0x22B0;
        inline constexpr std::uintptr_t bDespawnedDueToInactivity = 0x22D8;
        inline constexpr std::uintptr_t bDied = 0x22B0;
        inline constexpr std::uintptr_t bFrozen = 0x22B0;
        inline constexpr std::uintptr_t bFullBodyHitReact = 0x22B0;
        inline constexpr std::uintptr_t bHasGoalActor = 0x22B0;
        inline constexpr std::uintptr_t bHasInventory = 0x22D8;
        inline constexpr std::uintptr_t bHitReact = 0x22B0;
        inline constexpr std::uintptr_t bKilledOrDowned = 0x22D8;
        inline constexpr std::uintptr_t bNeedsDeathNotification = 0x22D8;
        inline constexpr std::uintptr_t bRangedAttacking = 0x22B0;
        inline constexpr std::uintptr_t bUseSharedAnimation = 0x22B4;
        inline constexpr std::uintptr_t DeimosBatchedGameplayCueParameters = 0x1EC0;
        inline constexpr std::uintptr_t RepAnimMontageInfo = 0x1FA0;
        inline constexpr std::uintptr_t RepSharedAnimInfo = 0x1FD8;
        inline constexpr std::uintptr_t SimulatedProxyGameplayCues = 0x1FF0;
    }

    namespace a_fort_athena_aircraft {
        inline constexpr std::uintptr_t bCanOverrideSkin = 0x300;
        inline constexpr std::uintptr_t bFlightExternalAuthoritative = 0x301;
        inline constexpr std::uintptr_t bPreventDestroyOnFlightEnd = 0x379;
        inline constexpr std::uintptr_t bWasSpawnedForAircraftPhase = 0x378;
        inline constexpr std::uintptr_t ClientFlightTimerDrift = 0x384;
        inline constexpr std::uintptr_t DropEndTime = 0x374;
        inline constexpr std::uintptr_t DropStartTime = 0x370;
        inline constexpr std::uintptr_t FlightElapsedTime = 0x380;
        inline constexpr std::uintptr_t FlightEndTime = 0x36C;
        inline constexpr std::uintptr_t FlightInfo = 0x320;
        inline constexpr std::uintptr_t FlightStartTime = 0x368;
        inline constexpr std::uintptr_t MiniMapIconBrush = 0x390;
        inline constexpr std::uintptr_t MinimapIconColorEnemy = 0x2C0;
        inline constexpr std::uintptr_t MinimapIconColorTeammate = 0x2B0;
        inline constexpr std::uintptr_t MiniMapIconScale = 0x38C;
        inline constexpr std::uintptr_t MiniMapTeamIndicatorIconScale = 0x440;
        inline constexpr std::uintptr_t NumSpawnSlots = 0x304;
        inline constexpr std::uintptr_t OnDropZoneExited = 0x2E0;
        inline constexpr std::uintptr_t ReplicatedFlightTimestamp = 0x37C;
        inline constexpr std::uintptr_t SpawnOffsetRadius = 0x308;
    }

    namespace a_fort_athena_supply_drop {
        inline constexpr std::uintptr_t bDisableAbilitySystemReplication = 0xA41;
        inline constexpr std::uintptr_t bReplicateLongUseNotifies = 0xA40;
        inline constexpr std::uintptr_t bVisualizePlayerInteractionChanges = 0xAAC;
        inline constexpr std::uintptr_t CachedInStormDespawnTimeInSeconds = 0xA78;
        inline constexpr std::uintptr_t CachedSpecialActorIdx = 0xA44;
        inline constexpr std::uintptr_t GroundCollsionProfile = 0x920;
        inline constexpr std::uintptr_t InStormDespawnTimeInSeconds = 0xA50;
        inline constexpr std::uintptr_t LastGroundLocationHitResult = 0x938;
        inline constexpr std::uintptr_t LinkToActorComponent = 0xAA0;
        inline constexpr std::uintptr_t LongInteractAudioComponent = 0xA80;
        inline constexpr std::uintptr_t LootTableNameOverride = 0x930;
        inline constexpr std::uintptr_t NumPlayersInteracting = 0xAA8;
        inline constexpr std::uintptr_t SearchingSoundCueLoop = 0xA38;
        inline constexpr std::uintptr_t SpawnOffsetZ = 0xA30;
        inline constexpr std::uintptr_t SpecialActorID = 0xA48;
        inline constexpr std::uintptr_t SpectatorMapIcon = 0xA98;
        inline constexpr std::uintptr_t WaveSpawnSoundCue = 0x928;
    }

    namespace a_fort_athena_vehicle {
        inline constexpr std::uintptr_t bUseDeprecatedSleepOnSpawn = 0x6D8;
        inline constexpr std::uintptr_t CustomName = 0x658;
        inline constexpr std::uintptr_t CustomOwnerAccountId = 0x628;
        inline constexpr std::uintptr_t CustomOwnerName = 0x608;
        inline constexpr std::uintptr_t DefaultOwnerName = 0x618;
        inline constexpr std::uintptr_t LastDamageInstigator = 0x758;
        inline constexpr std::uintptr_t NetPredictionProxy_AP = 0x5B8;
        inline constexpr std::uintptr_t NetPredictionProxy_SP = 0x5D0;
        inline constexpr std::uintptr_t OnActorRecentlyHit = 0x5A0;
        inline constexpr std::uintptr_t OnCurrentGearChangedDelegate = 0x5F8;
        inline constexpr std::uintptr_t OnScrapingSidesOrTopChangedDelegate = 0x5E8;
        inline constexpr std::uintptr_t OnSleepStateChangedDelegate = 0x6C8;
        inline constexpr std::uintptr_t OnSpringCompressionDelegate = 0x690;
        inline constexpr std::uintptr_t OverrideItemWrap = 0x688;
        inline constexpr std::uintptr_t PlayersBasedOnVehicle = 0x6A0;
        inline constexpr std::uintptr_t SoftOverrideItemWrap = 0x668;
        inline constexpr std::uintptr_t VehicleContextTag = 0x590;
        inline constexpr std::uintptr_t VehicleEventRouter = 0x598;
        inline constexpr std::uintptr_t VehicleImpactDamageTag = 0x5B0;
        inline constexpr std::uintptr_t WaterSurfaceDataCache = 0x6E0;
    }

    namespace a_fort_game_state {
        inline constexpr std::uintptr_t AnalyticsSessionInfo = 0x3A0;
        inline constexpr std::uintptr_t bCharacterCollectionEnabled = 0x3F9;
        inline constexpr std::uintptr_t bDBNOEnabledForGameMode = 0x3DC;
        inline constexpr std::uintptr_t bFishingCollectionEnabled = 0x3F8;
        inline constexpr std::uintptr_t bPlayerRespawningBlocked_Temporarily = 0x408;
        inline constexpr std::uintptr_t bShowLoadingScreenUntilAllLevelAreLoaded = 0x3DC;
        inline constexpr std::uintptr_t bSkipWorldSave = 0x3DC;
        inline constexpr std::uintptr_t CraftingBonus = 0x368;
        inline constexpr std::uintptr_t CurrentReadyToContinueTimer = 0x36C;
        inline constexpr std::uintptr_t CurrentWUID = 0x350;
        inline constexpr std::uintptr_t MatchmakingLinkId = 0x378;
        inline constexpr std::uintptr_t MatchmakingLinkType = 0x390;
        inline constexpr std::uintptr_t MatchStartTime = 0x3FC;
        inline constexpr std::uintptr_t ParTime = 0x360;
        inline constexpr std::uintptr_t POIManager = 0x3C0;
        inline constexpr std::uintptr_t RealMatchStartTime = 0x400;
        inline constexpr std::uintptr_t ReplicatedWorldRealTimeSecondsDouble = 0x410;
        inline constexpr std::uintptr_t ServerWorldRealTimeSecondsDelta = 0x418;
        inline constexpr std::uintptr_t TeamCount = 0x370;
        inline constexpr std::uintptr_t WorldLevel = 0x364;
    }

    namespace a_fort_game_state_athena {
        inline constexpr std::uintptr_t AthenaGameDataResetRows = 0x1198;
        inline constexpr std::uintptr_t AthenaGameDataTable = 0x1190;
        inline constexpr std::uintptr_t bBlockBuildOnWaterGlobal = 0x1091;
        inline constexpr std::uintptr_t bCanBuildOnWaterGlobal = 0x1090;
        inline constexpr std::uintptr_t bCanSpawnLoot = 0x10E9;
        inline constexpr std::uintptr_t bDisconnectOnContentBeaconError = 0x11B2;
        inline constexpr std::uintptr_t bInSpawningStartup = 0x1068;
        inline constexpr std::uintptr_t bIsGrassFireBoundsUpdateEnabled = 0x10E8;
        inline constexpr std::uintptr_t bIsUsingDownloadOnDemand = 0x11B0;
        inline constexpr std::uintptr_t bPlaylistDataIsActivelyLoading = 0x1262;
        inline constexpr std::uintptr_t bPlaylistDataIsLoaded = 0x1260;
        inline constexpr std::uintptr_t bWantsHoldoverPluginOnClient = 0x11B1;
        inline constexpr std::uintptr_t InfiniteBuildingResources = 0x10F0;
        inline constexpr std::uintptr_t InfiniteGold = 0x1118;
        inline constexpr std::uintptr_t InfiniteWorldResources = 0x1140;
        inline constexpr std::uintptr_t OnCurrentPlaylistLoaded = 0x11F0;
        inline constexpr std::uintptr_t OnNewContentUpdateMessageRecieved = 0x10C8;
        inline constexpr std::uintptr_t OnNewScreenLogMessageReceived = 0x10D8;
        inline constexpr std::uintptr_t PostGameUIInfo = 0x1060;
        inline constexpr std::uintptr_t ResetAthenaGameDataTable = 0x11A8;
    }

    namespace a_fort_inventory {
        inline constexpr std::uintptr_t bIsShuttingDown = 0x36E;
        inline constexpr std::uintptr_t bRequiresLocalUpdate = 0x36C;
        inline constexpr std::uintptr_t bRequiresSaving = 0x36D;
        inline constexpr std::uintptr_t Inventory = 0x2C0;
        inline constexpr std::uintptr_t InventoryType = 0x2B9;
        inline constexpr std::uintptr_t PendingExistingItems = 0x348;
        inline constexpr std::uintptr_t PendingInstances = 0x388;
        inline constexpr std::uintptr_t RecentlyAdded = 0x278;
        inline constexpr std::uintptr_t RecentlyChanged = 0x298;
        inline constexpr std::uintptr_t RecentlyRemoved = 0x288;
        inline constexpr std::uintptr_t ReplayPawn = 0x364;
    }

    namespace a_fort_pawn {
        inline constexpr std::uintptr_t bAllowDeathFromFallingDamage = 0x720;
        inline constexpr std::uintptr_t BatchedGameplayCueParameters = 0x0;
        inline constexpr std::uintptr_t bCanCapsuleBeUsedForTargeting = 0x721;
        inline constexpr std::uintptr_t bIgnoreNextFallingDamage = 0x720;
        inline constexpr std::uintptr_t bIsDying = 0x720;
        inline constexpr std::uintptr_t bIsHiddenForDeath = 0x720;
        inline constexpr std::uintptr_t bIsInvulnerable = 0x722;
        inline constexpr std::uintptr_t bIsKnockedback = 0x721;
        inline constexpr std::uintptr_t bIsStaggered = 0x721;
        inline constexpr std::uintptr_t bMovingEmote = 0x721;
        inline constexpr std::uintptr_t bMovingEmoteFollowingOnly = 0x722;
        inline constexpr std::uintptr_t bMovingEmoteForwardOnly = 0x721;
        inline constexpr std::uintptr_t bMovingEmoteSkipLandingFX = 0x722;
        inline constexpr std::uintptr_t bPlayedDying = 0x720;
        inline constexpr std::uintptr_t bPrimaryInputHeld = 0x722;
        inline constexpr std::uintptr_t bRegisterWithAimAssist = 0x722;
        inline constexpr std::uintptr_t bRegisterWithAISight = 0x722;
        inline constexpr std::uintptr_t bSecondaryInputHeld = 0x722;
        inline constexpr std::uintptr_t bUseBaseChanged = 0x720;
        inline constexpr std::uintptr_t bUseLineTestForDamageZoneBoneDetection = 0x721;
    }

    namespace a_fort_physics_pawn {
        inline constexpr std::uintptr_t bUseNetPrediction = 0x334;
        inline constexpr std::uintptr_t GravityMultiplier = 0x330;
        inline constexpr std::uintptr_t ReplicatedTransformReq = 0x2F8;
    }

    namespace a_fort_pickup {
        inline constexpr std::uintptr_t bAutoUpgradeWeapons = 0x28D;
        inline constexpr std::uintptr_t bBlockedFromAutoPickup = 0x28B;
        inline constexpr std::uintptr_t bCanBeMarked = 0x28C;
        inline constexpr std::uintptr_t bClientUseInterpolationOnly = 0x28D;
        inline constexpr std::uintptr_t bCombinePickupsWhenTossCompletes = 0x28C;
        inline constexpr std::uintptr_t bDoServerHandlePickupTrace = 0x28D;
        inline constexpr std::uintptr_t bForceDefaultFlyTime = 0x28D;
        inline constexpr std::uintptr_t bForceHideMinimapIndicator = 0x28C;
        inline constexpr std::uintptr_t bPickedUp = 0x28C;
        inline constexpr std::uintptr_t bRandomRotation = 0x28C;
        inline constexpr std::uintptr_t bServerStoppedSimulation = 0x28D;
        inline constexpr std::uintptr_t bSplitOnPickup = 0x28C;
        inline constexpr std::uintptr_t bSuppressInteractionWidget = 0x28D;
        inline constexpr std::uintptr_t bTossedFromContainer = 0x28C;
        inline constexpr std::uintptr_t bUsePickupWidget = 0x28D;
        inline constexpr std::uintptr_t bWeaponsCanBeAutoPickups = 0x28D;
        inline constexpr std::uintptr_t PickupSourceTypeFlags = 0x288;
        inline constexpr std::uintptr_t PickupSpawnSource = 0x289;
        inline constexpr std::uintptr_t ServerImpactSoundFlash = 0x28A;
        inline constexpr std::uintptr_t SimulatingTooLongLength = 0x290;
    }

    namespace a_fort_player_controller {
        inline constexpr std::uintptr_t AircraftInputComponent = 0x9C0;
        inline constexpr std::uintptr_t bAssignedStartSpawn = 0x9D8;
        inline constexpr std::uintptr_t bClientPawnIsLoaded = 0x9D8;
        inline constexpr std::uintptr_t bHasInitiallySpawned = 0x9D8;
        inline constexpr std::uintptr_t bInPossession = 0x951;
        inline constexpr std::uintptr_t bIsBeingKicked = 0x9D8;
        inline constexpr std::uintptr_t bTrapsInNoBuild = 0x848;
        inline constexpr std::uintptr_t bUnlockAllZones = 0x730;
        inline constexpr std::uintptr_t HybridControlsComponentComponent = 0x998;
        inline constexpr std::uintptr_t OnControllerComponentAttachedEvent = 0x878;
        inline constexpr std::uintptr_t OnEnteredEditMode = 0x770;
        inline constexpr std::uintptr_t OnFortPawnChangedEvent = 0x850;
        inline constexpr std::uintptr_t OnInputFiltered = 0x820;
        inline constexpr std::uintptr_t OnLoadoutChanged = 0x790;
        inline constexpr std::uintptr_t OnPickupCreated = 0x780;
        inline constexpr std::uintptr_t OnPlayerPawnPossessed = 0x760;
        inline constexpr std::uintptr_t OnPlayerStateReady = 0x810;
        inline constexpr std::uintptr_t OnViewTargetChanged = 0x7D0;
        inline constexpr std::uintptr_t SkydiveMusicAudioComp = 0x9D0;
        inline constexpr std::uintptr_t SprintOverrideComponent = 0x9C8;
    }

    namespace a_fort_player_controller_athena {
        inline constexpr std::uintptr_t bAllowPlayersCreditOnLeave = 0x3725;
        inline constexpr std::uintptr_t bLockingOnFocalPoint = 0x3726;
        inline constexpr std::uintptr_t bSkipPlayWinEffects = 0x3724;
        inline constexpr std::uintptr_t FireAbilityToWeaponSwitchTime = 0x3680;
        inline constexpr std::uintptr_t FocalPoint = 0x3728;
        inline constexpr std::uintptr_t FocalPointDuration = 0x374C;
        inline constexpr std::uintptr_t FocalPointFOV = 0x3748;
        inline constexpr std::uintptr_t FocalPointOffset = 0x3730;
        inline constexpr std::uintptr_t InterpolatedSkydiveFollowerViewRotation = 0x37E8;
        inline constexpr std::uintptr_t OnAircraftStateChange = 0x36B0;
        inline constexpr std::uintptr_t OnCinematicCameraSkipped = 0x3778;
        inline constexpr std::uintptr_t OnClientDonationSuccessDelegate = 0x3798;
        inline constexpr std::uintptr_t OnFocalPointActorChanged = 0x3768;
        inline constexpr std::uintptr_t OnItemDroppedDueToOverflow = 0x3708;
        inline constexpr std::uintptr_t OnItemDropSpawnedDelegate = 0x36F8;
        inline constexpr std::uintptr_t OnSkydiveLeaderChanged = 0x3788;
        inline constexpr std::uintptr_t OnUsingFocalPointChanged = 0x3758;
        inline constexpr std::uintptr_t SkydiveLeaderManualCameraTime = 0x37E0;
        inline constexpr std::uintptr_t SwappingItemDefinition = 0x3718;
        inline constexpr std::uintptr_t WinScreenDelayTime = 0x3720;
    }

    namespace a_fort_player_controller_zone {
        inline constexpr std::uintptr_t bClientNotifiedOfPawnDied = 0x3260;
        inline constexpr std::uintptr_t bUseDeferredFireInputs = 0x3110;
        inline constexpr std::uintptr_t DeathInputComponent = 0x30D8;
        inline constexpr std::uintptr_t GadgetTrackedAttributeItemInstanceIds = 0x3060;
        inline constexpr std::uintptr_t LastVehicleSeatSwitchTime = 0x3040;
        inline constexpr std::uintptr_t MarkerComponent = 0x30E8;
        inline constexpr std::uintptr_t NumRefundForceQueryProfileRequestsInFlight = 0x305C;
        inline constexpr std::uintptr_t OnBeginSkydiving = 0x2FE0;
        inline constexpr std::uintptr_t OnBeginSkydivingFromBus = 0x3000;
        inline constexpr std::uintptr_t OnEndSkydiving = 0x2FF0;
        inline constexpr std::uintptr_t OnEndSkydivingFromBus = 0x3010;
        inline constexpr std::uintptr_t OnStartedRespawn = 0x3030;
        inline constexpr std::uintptr_t OnVehicleSeatTransitionTargetIndexChange = 0x3020;
        inline constexpr std::uintptr_t PlayerDeathReport = 0x3138;
        inline constexpr std::uintptr_t PlayerToSpectateOnDeath = 0x3050;
        inline constexpr std::uintptr_t PurchaseCatalogEntryComponent = 0x30C8;
        inline constexpr std::uintptr_t RefundMtxPurchaseComponent = 0x30D0;
        inline constexpr std::uintptr_t RemoteControlledPawnInputComponent = 0x30E0;
        inline constexpr std::uintptr_t SpectatorModeComponent = 0x30C0;
        inline constexpr std::uintptr_t TriggerHapticsComponent = 0x30B8;
    }

    namespace a_fort_player_pawn {
        inline constexpr std::uintptr_t bBalloonMovementActivated = 0x1F7C;
        inline constexpr std::uintptr_t bBuildHotfix = 0x1F7C;
        inline constexpr std::uintptr_t bDisableSwimSprintCancel = 0x1F7B;
        inline constexpr std::uintptr_t bDoSafeZoneCleanup = 0x1F7A;
        inline constexpr std::uintptr_t bForceAllowClothingActor = 0x1F7C;
        inline constexpr std::uintptr_t bHasDisableSprintTag = 0x1F7A;
        inline constexpr std::uintptr_t bIsNearSafeZoneEdge = 0x1F7A;
        inline constexpr std::uintptr_t bIsScriptedBot = 0x1F7C;
        inline constexpr std::uintptr_t bIsSprintJump = 0x1F7A;
        inline constexpr std::uintptr_t bIsSwappingCharacterParts = 0x1F7C;
        inline constexpr std::uintptr_t bIsSwimmingAnimLayerLinked = 0x1F7A;
        inline constexpr std::uintptr_t bIsSwimmingAnimLayerPendingRemove = 0x1F7A;
        inline constexpr std::uintptr_t bIsTacticalSprinting = 0x1F7A;
        inline constexpr std::uintptr_t bIsTargeting = 0x1F7C;
        inline constexpr std::uintptr_t bIsWaterJump = 0x1F7B;
        inline constexpr std::uintptr_t bIsWaterSprintBoost = 0x1F7B;
        inline constexpr std::uintptr_t bIsWaterSprintBoostPending = 0x1F7B;
        inline constexpr std::uintptr_t bPlayingPassengerToPassengerAnimation = 0x1F7B;
        inline constexpr std::uintptr_t bPlayingSafeZoneEffects = 0x1F7A;
        inline constexpr std::uintptr_t VehicleInputStateReliable = 0x1F78;
    }

    namespace a_fort_player_pawn_athena {
        inline constexpr std::uintptr_t BecameSpecialActorTime = 0x49EC;
        inline constexpr std::uintptr_t bPlaytestWithNoMouse = 0x49F0;
        inline constexpr std::uintptr_t bWasCrouchedBeforeDBNO = 0x49D0;
        inline constexpr std::uintptr_t CachedDBNOInvulnerableTime = 0x49B8;
        inline constexpr std::uintptr_t CanBeDamagedInDBNO = 0x498C;
        inline constexpr std::uintptr_t ConvertFromDBNOTime = 0x49BC;
        inline constexpr std::uintptr_t DBNOInvulnerableTime = 0x49B4;
        inline constexpr std::uintptr_t DBNOStartLocation = 0x4998;
        inline constexpr std::uintptr_t DBNOStartTime = 0x4990;
        inline constexpr std::uintptr_t DeathTime = 0x49B0;
        inline constexpr std::uintptr_t ItemInteractionActor = 0x4940;
        inline constexpr std::uintptr_t ItemSpecialActorCategoryTag = 0x49E4;
        inline constexpr std::uintptr_t ItemSpecialActorID = 0x49E0;
        inline constexpr std::uintptr_t LandEmitterTemplate = 0x4A00;
        inline constexpr std::uintptr_t LastCrouchUpdateTime = 0x49D8;
        inline constexpr std::uintptr_t OnInteractionFailedCallback = 0x4930;
        inline constexpr std::uintptr_t OnReviveSound = 0x4980;
        inline constexpr std::uintptr_t PreviousVelocityXY = 0x4968;
        inline constexpr std::uintptr_t ReviveFromDBNOTime = 0x4988;
        inline constexpr std::uintptr_t ServerWorldTimeRevivalTime = 0x49C0;
    }

    namespace a_fort_player_state {
        inline constexpr std::uintptr_t Banner = 0x410;
        inline constexpr std::uintptr_t bHasFinishedLoading = 0x388;
        inline constexpr std::uintptr_t bHasStartedPlaying = 0x388;
        inline constexpr std::uintptr_t bIsGameSessionAdmin = 0x388;
        inline constexpr std::uintptr_t bIsGameSessionOwner = 0x388;
        inline constexpr std::uintptr_t bIsReadyToContinue = 0x388;
        inline constexpr std::uintptr_t bIsWorldDataOwner = 0x388;
        inline constexpr std::uintptr_t bRepFlag1 = 0x388;
        inline constexpr std::uintptr_t CachedLoadoutCharacterInfo = 0x438;
        inline constexpr std::uintptr_t CurrentCharXP = 0x3D8;
        inline constexpr std::uintptr_t ExperienceDeltas = 0x3F0;
        inline constexpr std::uintptr_t HeroId = 0x3C0;
        inline constexpr std::uintptr_t HeroType = 0x3D0;
        inline constexpr std::uintptr_t InitialExperienceAmount = 0x3E8;
        inline constexpr std::uintptr_t InitialExperienceLevel = 0x3E4;
        inline constexpr std::uintptr_t MyBackpackPickup = 0x3DC;
        inline constexpr std::uintptr_t PartyOwnerUniqueId = 0x390;
        inline constexpr std::uintptr_t Platform = 0x400;
        inline constexpr std::uintptr_t PlayerRole = 0x38C;
        inline constexpr std::uintptr_t WorldPlayerId = 0x38E;
    }

    namespace a_fort_player_state_athena {
        inline constexpr std::uintptr_t AIKillCount = 0xF94;
        inline constexpr std::uintptr_t AlwaysIncludeTeamAsAllies = 0xF30;
        inline constexpr std::uintptr_t bHasWonAGame = 0xF08;
        inline constexpr std::uintptr_t bTeamPlacementLocked = 0xF3C;
        inline constexpr std::uintptr_t DamageDealtToBigHealthProps = 0xF20;
        inline constexpr std::uintptr_t DownScore = 0xF44;
        inline constexpr std::uintptr_t HumanKillScore = 0xF54;
        inline constexpr std::uintptr_t KillScore = 0xF48;
        inline constexpr std::uintptr_t KillsWhileAthenaGadgetEquippedMap = 0xF10;
        inline constexpr std::uintptr_t NumAmmoCansOpened = 0xFA4;
        inline constexpr std::uintptr_t NumChestsOpened = 0xF9C;
        inline constexpr std::uintptr_t OnSquadIdChangedDelegate = 0xEC8;
        inline constexpr std::uintptr_t PersonalLobbyAction = 0xE54;
        inline constexpr std::uintptr_t Place = 0xF40;
        inline constexpr std::uintptr_t RespawnData = 0xE58;
        inline constexpr std::uintptr_t SeasonLevelUIDisplay = 0xF4C;
        inline constexpr std::uintptr_t TeamIndex = 0xF31;
        inline constexpr std::uintptr_t TeamKillScore = 0xF0C;
        inline constexpr std::uintptr_t TeamScore = 0xF38;
        inline constexpr std::uintptr_t TeamScorePlacement = 0xF34;
    }

    namespace a_fort_player_state_zone {
        inline constexpr std::uintptr_t bInvincibleDueToUI = 0xCD0;
        inline constexpr std::uintptr_t CarriedObject = 0xCA8;
        inline constexpr std::uintptr_t CurrentHealth = 0xCD4;
        inline constexpr std::uintptr_t CurrentShield = 0xCDC;
        inline constexpr std::uintptr_t KickedFromSessionReason = 0xB78;
        inline constexpr std::uintptr_t MaxHealth = 0xCD8;
        inline constexpr std::uintptr_t NumRejoins = 0xCB0;
        inline constexpr std::uintptr_t OldTotalScoreStat = 0xCB4;
        inline constexpr std::uintptr_t OnBeginSpectatingEvent = 0xB50;
        inline constexpr std::uintptr_t OnCurrentPawnChanged = 0xA60;
        inline constexpr std::uintptr_t OnSpectatingPlayerAddedEvent = 0xB00;
        inline constexpr std::uintptr_t OnSpectatingPlayerRemovedEvent = 0xB10;
        inline constexpr std::uintptr_t OnSpectatingTargetChangedEvent = 0xB40;
        inline constexpr std::uintptr_t OnSpectatorCountChangedEvent = 0xB30;
        inline constexpr std::uintptr_t OnSpectatorsAddedEvent = 0xAF0;
        inline constexpr std::uintptr_t OnSpectatorsRemovedEvent = 0xB20;
        inline constexpr std::uintptr_t OtherPlayersSpectatingCurrentTarget = 0xC98;
        inline constexpr std::uintptr_t RS_Zone_Old = 0xB7C;
        inline constexpr std::uintptr_t SpectatingTarget = 0xA88;
        inline constexpr std::uintptr_t Spectators = 0xA90;
    }

    namespace a_fort_projectile_base {
        inline constexpr std::uintptr_t bAddOwnerVelocity = 0x6D8;
        inline constexpr std::uintptr_t bCanBePickedUpWhenStopped = 0x748;
        inline constexpr std::uintptr_t bRegisterInPerceptionSystem = 0x738;
        inline constexpr std::uintptr_t bSpawnPointCanBeUsedByOtherPlayers = 0x730;
        inline constexpr std::uintptr_t CapsuleComponent = 0x750;
        inline constexpr std::uintptr_t ChargePercent = 0x6D0;
        inline constexpr std::uintptr_t ChargeUpInitialSpeed = 0x690;
        inline constexpr std::uintptr_t GravityScale = 0x6C4;
        inline constexpr std::uintptr_t InitialGravityScaleOverride = 0x6B0;
        inline constexpr std::uintptr_t InitialSpeed = 0x680;
        inline constexpr std::uintptr_t MaxDeltaVelocityAngleToOwnerVelocity = 0x708;
        inline constexpr std::uintptr_t MaxInitialSpeedForOwnerVelocity = 0x6E0;
        inline constexpr std::uintptr_t MaxSpeed = 0x6A0;
        inline constexpr std::uintptr_t MomentumTransfer = 0x6D4;
        inline constexpr std::uintptr_t OriginalTarget = 0x6C8;
        inline constexpr std::uintptr_t PlayerSpawnOffset = 0x734;
        inline constexpr std::uintptr_t ProjectileMovementComponent = 0x758;
        inline constexpr std::uintptr_t ReplicatedMaxSpeed = 0x6C0;
        inline constexpr std::uintptr_t StaticMeshPropToRemoveOnPawn = 0x740;
        inline constexpr std::uintptr_t VerticleFireOffset = 0x670;
    }

    namespace a_fort_safe_zone_indicator {
        inline constexpr std::uintptr_t bMotionExternalAuthoritative = 0x2ED;
        inline constexpr std::uintptr_t bPaused = 0x2EE;
        inline constexpr std::uintptr_t bPausedForPreview = 0x2EF;
        inline constexpr std::uintptr_t bPausedForPreview_Previous = 0x2F0;
        inline constexpr std::uintptr_t bSafezoneEventDriven = 0x2EC;
        inline constexpr std::uintptr_t bSafeZoneStateChangeAudioDisabled = 0x2F1;
        inline constexpr std::uintptr_t CurrentTravelSplineComponent = 0x2E0;
        inline constexpr std::uintptr_t MinimapComp = 0x270;
        inline constexpr std::uintptr_t NextCenter = 0x2A0;
        inline constexpr std::uintptr_t NextNextCenter = 0x2B8;
        inline constexpr std::uintptr_t NextNextRadius = 0x280;
        inline constexpr std::uintptr_t NextRadius = 0x27C;
        inline constexpr std::uintptr_t NextRotation = 0x2D4;
        inline constexpr std::uintptr_t NextShapeId = 0x2DC;
        inline constexpr std::uintptr_t PlaylistMaxSafeZoneIndex = 0x2F4;
        inline constexpr std::uintptr_t PreviousCenter = 0x288;
        inline constexpr std::uintptr_t PreviousRadius = 0x278;
        inline constexpr std::uintptr_t PreviousRotation = 0x2D0;
        inline constexpr std::uintptr_t PreviousShapeId = 0x2D8;
        inline constexpr std::uintptr_t StormEffectDelayOverride = 0x2E8;
    }

    namespace a_fort_weapon {
        inline constexpr std::uintptr_t bCheckCollisionsWithoutAbility = 0x381;
        inline constexpr std::uintptr_t bDisableEquipAnimation = 0x381;
        inline constexpr std::uintptr_t bIsAimingConsumable = 0x3A8;
        inline constexpr std::uintptr_t bIsChargingWeapon = 0x380;
        inline constexpr std::uintptr_t bIsEquippingWeapon = 0x368;
        inline constexpr std::uintptr_t bIsReloadingWeapon = 0x381;
        inline constexpr std::uintptr_t bNeverUpdateLastFireTimeOnImpactForLocalClient = 0x34C;
        inline constexpr std::uintptr_t IsEquippingWeaponChanged = 0x370;
        inline constexpr std::uintptr_t OnLocalAmmoChanged = 0x420;
        inline constexpr std::uintptr_t OnLocalReloadCancelled = 0x468;
        inline constexpr std::uintptr_t OnLocalReloadStarted = 0x430;
        inline constexpr std::uintptr_t OnLocalTargetingChanged = 0x490;
        inline constexpr std::uintptr_t OnPressTrigger = 0x2E0;
        inline constexpr std::uintptr_t OnReleaseTrigger = 0x2F0;
        inline constexpr std::uintptr_t OnReloadStarted = 0x440;
        inline constexpr std::uintptr_t OnSecondaryAbilityToggled = 0x4B0;
        inline constexpr std::uintptr_t OnTargetingChanged = 0x4A0;
        inline constexpr std::uintptr_t OnWeaponRateOfFireChanged = 0x2B8;
        inline constexpr std::uintptr_t OnWeaponRateOfFireScaleChanged = 0x2C8;
        inline constexpr std::uintptr_t TimeToEquip = 0x348;
    }

    namespace a_fort_weapon_ranged {
        inline constexpr std::uintptr_t bAllowAutomaticWeaponCatchup = 0x1D30;
        inline constexpr std::uintptr_t bLWPNudgeHitOrigin = 0x1AF8;
        inline constexpr std::uintptr_t CurrentNumBullets = 0x1D5C;
        inline constexpr std::uintptr_t HitscanTracerFakeVelocity = 0x1D20;
        inline constexpr std::uintptr_t LocalFireRateModification = 0x1D58;
        inline constexpr std::uintptr_t LWPNudgeHitDistance = 0x1B00;
        inline constexpr std::uintptr_t MuzzleFXData = 0x1C70;
        inline constexpr std::uintptr_t NDCTracerFx = 0x1B38;
        inline constexpr std::uintptr_t OnBulletTracerBeamFXActivated = 0x1900;
        inline constexpr std::uintptr_t OnBulletTracerNiagaraDataSent = 0x18F0;
        inline constexpr std::uintptr_t OnProjectileSpawned = 0x18D0;
        inline constexpr std::uintptr_t OnRecoilAdded = 0x18E0;
        inline constexpr std::uintptr_t PlayDelayedFiringAnimationTimerHandle = 0x1AE8;
        inline constexpr std::uintptr_t PlayDelayedRecoilTimerHandle = 0x1AE0;
        inline constexpr std::uintptr_t PlayDelayedSpreadTimerHandle = 0x1AF0;
        inline constexpr std::uintptr_t ReplayActivationCue = 0x1928;
        inline constexpr std::uintptr_t ReplayImpactCue = 0x1A00;
        inline constexpr std::uintptr_t ScopeTargetingMuzzleOffset = 0x1D60;
        inline constexpr std::uintptr_t TracerFXDataChannel = 0x1B30;
        inline constexpr std::uintptr_t TracerTemplate = 0x1D28;
    }

    namespace a_pawn {
        inline constexpr std::uintptr_t AIControllerClass = 0x288;
        inline constexpr std::uintptr_t AutoPossessAI = 0x281;
        inline constexpr std::uintptr_t AutoPossessPlayer = 0x280;
        inline constexpr std::uintptr_t BaseEyeHeight = 0x27C;
        inline constexpr std::uintptr_t bCanAffectNavigationGeneration = 0x278;
        inline constexpr std::uintptr_t bIsLocalViewTarget = 0x278;
        inline constexpr std::uintptr_t bUseControllerRotationPitch = 0x278;
        inline constexpr std::uintptr_t bUseControllerRotationRoll = 0x278;
        inline constexpr std::uintptr_t bUseControllerRotationYaw = 0x278;
        inline constexpr std::uintptr_t ControlInputVector = 0x2B8;
        inline constexpr std::uintptr_t Controller = 0x2A0;
        inline constexpr std::uintptr_t LastControlInputVector = 0x2D0;
        inline constexpr std::uintptr_t LastHitBy = 0x298;
        inline constexpr std::uintptr_t OverrideInputComponentClass = 0x2E8;
        inline constexpr std::uintptr_t PlayerState = 0x290;
        inline constexpr std::uintptr_t PreviousController = 0x2A8;
        inline constexpr std::uintptr_t ReceiveControllerChangedDelegate = 0x2B4;
        inline constexpr std::uintptr_t ReceiveRestartedDelegate = 0x2B5;
        inline constexpr std::uintptr_t RemoteViewPitch = 0x284;
        inline constexpr std::uintptr_t RemoteViewPitch16 = 0x282;
    }

    namespace a_player_camera_manager {
        inline constexpr std::uintptr_t AnimCameraActor = 0x2898;
        inline constexpr std::uintptr_t bAutoCalculateOrthoPlanes = 0x28A0;
        inline constexpr std::uintptr_t CachedCameraShakeMod = 0x2860;
        inline constexpr std::uintptr_t CameraCachePrivate = 0x1590;
        inline constexpr std::uintptr_t CameraLensEffects = 0x2850;
        inline constexpr std::uintptr_t DefaultAspectRatio = 0x294;
        inline constexpr std::uintptr_t DefaultFOV = 0x284;
        inline constexpr std::uintptr_t DefaultModifiers = 0x27E0;
        inline constexpr std::uintptr_t DefaultOrthoWidth = 0x28C;
        inline constexpr std::uintptr_t FreeCamDistance = 0x27F0;
        inline constexpr std::uintptr_t FreeCamOffset = 0x27F8;
        inline constexpr std::uintptr_t LastFrameCameraCachePrivate = 0x1EB0;
        inline constexpr std::uintptr_t ModifierList = 0x27D0;
        inline constexpr std::uintptr_t OnAudioFadeChangeEvent = 0x2828;
        inline constexpr std::uintptr_t PCOwner = 0x270;
        inline constexpr std::uintptr_t PendingViewTarget = 0xC30;
        inline constexpr std::uintptr_t PostProcessBlendCache = 0x2868;
        inline constexpr std::uintptr_t TransformComponent = 0x278;
        inline constexpr std::uintptr_t ViewTarget = 0x300;
        inline constexpr std::uintptr_t ViewTargetOffset = 0x2810;
    }

    namespace a_player_controller {
        inline constexpr std::uintptr_t AcknowledgedPawn = 0x318;
        inline constexpr std::uintptr_t ActiveForceFeedbackEffects = 0x3F0;
        inline constexpr std::uintptr_t bAutoManageActiveCameraTarget = 0x338;
        inline constexpr std::uintptr_t bPlayerIsWaiting = 0x480;
        inline constexpr std::uintptr_t CheatClass = 0x3E0;
        inline constexpr std::uintptr_t CheatManager = 0x3D8;
        inline constexpr std::uintptr_t ClientCap = 0x3D0;
        inline constexpr std::uintptr_t HiddenActors = 0x378;
        inline constexpr std::uintptr_t HiddenPrimitiveComponents = 0x388;
        inline constexpr std::uintptr_t LastSpectatorStateSynchTime = 0x39C;
        inline constexpr std::uintptr_t LastSpectatorSyncLocation = 0x3A0;
        inline constexpr std::uintptr_t LastSpectatorSyncRotation = 0x3B8;
        inline constexpr std::uintptr_t MyHUD = 0x320;
        inline constexpr std::uintptr_t NetPlayerIndex = 0x484;
        inline constexpr std::uintptr_t player = 0x310;
        inline constexpr std::uintptr_t PlayerCameraManager = 0x328;
        inline constexpr std::uintptr_t PlayerCameraManagerClass = 0x330;
        inline constexpr std::uintptr_t PlayerInput = 0x3E8;
        inline constexpr std::uintptr_t SmoothTargetViewRotationSpeed = 0x370;
        inline constexpr std::uintptr_t TargetViewRotation = 0x340;
    }

    namespace a_player_state {
        inline constexpr std::uintptr_t bFromPreviousLevel = 0x27A;
        inline constexpr std::uintptr_t bIsABot = 0x27A;
        inline constexpr std::uintptr_t bIsInactive = 0x27A;
        inline constexpr std::uintptr_t bIsSpectator = 0x27A;
        inline constexpr std::uintptr_t bOnlySpectator = 0x27A;
        inline constexpr std::uintptr_t bShouldUpdateReplicatedPing = 0x27A;
        inline constexpr std::uintptr_t CompressedPing = 0x278;
        inline constexpr std::uintptr_t EngineMessageClass = 0x2B0;
        inline constexpr std::uintptr_t OnPawnSet = 0x2D8;
        inline constexpr std::uintptr_t PawnPrivate = 0x2E8;
        inline constexpr std::uintptr_t PlayerID = 0x274;
        inline constexpr std::uintptr_t PlayerNamePrivate = 0x308;
        inline constexpr std::uintptr_t SavedNetworkAddress = 0x2C0;
        inline constexpr std::uintptr_t Score = 0x270;
        inline constexpr std::uintptr_t StartTime = 0x27C;
        inline constexpr std::uintptr_t UniqueID = 0x280;
    }

    namespace ahud {
        inline constexpr std::uintptr_t bEnableDebugTextShadow = 0x280;
        inline constexpr std::uintptr_t bLostFocusPaused = 0x278;
        inline constexpr std::uintptr_t bShowDebugInfo = 0x278;
        inline constexpr std::uintptr_t bShowHitBoxDebugInfo = 0x280;
        inline constexpr std::uintptr_t bShowHUD = 0x278;
        inline constexpr std::uintptr_t bShowOverlays = 0x280;
        inline constexpr std::uintptr_t canvas = 0x2C0;
        inline constexpr std::uintptr_t CurrentTargetIndex = 0x27C;
        inline constexpr std::uintptr_t DebugCanvas = 0x2C8;
        inline constexpr std::uintptr_t DebugDisplay = 0x2A0;
        inline constexpr std::uintptr_t DebugTextList = 0x2D0;
        inline constexpr std::uintptr_t PlayerOwner = 0x270;
        inline constexpr std::uintptr_t PostRenderedActors = 0x288;
        inline constexpr std::uintptr_t ShowDebugTargetActor = 0x2E8;
        inline constexpr std::uintptr_t ShowDebugTargetDesiredClass = 0x2E0;
        inline constexpr std::uintptr_t ToggledDebugCategories = 0x2B0;
    }

    namespace f_based_movement_info {
        inline constexpr std::uintptr_t BaseID = 0x0;
        inline constexpr std::uintptr_t BoneName = 0x4;
        inline constexpr std::uintptr_t bRelativeRotation = 0x2;
        inline constexpr std::uintptr_t bServerHasBaseComponent = 0x2;
        inline constexpr std::uintptr_t bServerHasVelocity = 0x2;
        inline constexpr std::uintptr_t Location = 0x10;
        inline constexpr std::uintptr_t MovementBase = 0x8;
        inline constexpr std::uintptr_t MovementBaseInterfaceData = 0x40;
        inline constexpr std::uintptr_t Rotation = 0x28;
    }

    namespace f_box {
        inline constexpr std::uintptr_t IsValid = 0x30;
        inline constexpr std::uintptr_t max = 0x18;
        inline constexpr std::uintptr_t min = 0x0;
    }

    namespace f_box_sphere_bounds {
        inline constexpr std::uintptr_t BoxExtent = 0x18;
        inline constexpr std::uintptr_t origin = 0x0;
        inline constexpr std::uintptr_t SphereRadius = 0x30;
    }

    namespace f_camera_cache_entry {
        inline constexpr std::uintptr_t POV = 0x10;
        inline constexpr std::uintptr_t Timestamp = 0x0;
    }

    namespace f_color {
        inline constexpr std::uintptr_t A = 0x3;
        inline constexpr std::uintptr_t B = 0x0;
        inline constexpr std::uintptr_t G = 0x1;
        inline constexpr std::uintptr_t R = 0x2;
    }

    namespace f_int_point {
        inline constexpr std::uintptr_t X = 0x0;
        inline constexpr std::uintptr_t Y = 0x4;
    }

    namespace f_int_vector {
        inline constexpr std::uintptr_t X = 0x0;
        inline constexpr std::uintptr_t Y = 0x4;
        inline constexpr std::uintptr_t Z = 0x8;
    }

    namespace f_linear_color {
        inline constexpr std::uintptr_t A = 0xC;
        inline constexpr std::uintptr_t B = 0x8;
        inline constexpr std::uintptr_t G = 0x4;
        inline constexpr std::uintptr_t R = 0x0;
    }

    namespace f_matrix {
        inline constexpr std::uintptr_t WPlane = 0x60;
        inline constexpr std::uintptr_t XPlane = 0x0;
        inline constexpr std::uintptr_t YPlane = 0x20;
        inline constexpr std::uintptr_t ZPlane = 0x40;
    }

    namespace f_minimal_view_info {
        inline constexpr std::uintptr_t AspectRatio = 0x5C;
        inline constexpr std::uintptr_t AutoPlaneShift = 0x48;
        inline constexpr std::uintptr_t bAutoCalculateOrthoPlanes = 0x44;
        inline constexpr std::uintptr_t bConstrainAspectRatio = 0x68;
        inline constexpr std::uintptr_t bUpdateOrthoPlanes = 0x4C;
        inline constexpr std::uintptr_t bUseCameraHeightAsViewTarget = 0x4D;
        inline constexpr std::uintptr_t bUseFieldOfViewForLOD = 0x68;
        inline constexpr std::uintptr_t bUseFirstPersonParameters = 0x68;
        inline constexpr std::uintptr_t DesiredFOV = 0x34;
        inline constexpr std::uintptr_t FirstPersonFOV = 0x38;
        inline constexpr std::uintptr_t FirstPersonScale = 0x3C;
        inline constexpr std::uintptr_t FOV = 0x30;
        inline constexpr std::uintptr_t Location = 0x0;
        inline constexpr std::uintptr_t OrthoFarClipPlane = 0x54;
        inline constexpr std::uintptr_t OrthoNearClipPlane = 0x50;
        inline constexpr std::uintptr_t OrthoWidth = 0x40;
        inline constexpr std::uintptr_t PerspectiveNearClipPlane = 0x58;
        inline constexpr std::uintptr_t PostProcessBlendWeight = 0x70;
        inline constexpr std::uintptr_t ProjectionMode = 0x6C;
        inline constexpr std::uintptr_t Rotation = 0x18;
    }

    namespace f_quat {
        inline constexpr std::uintptr_t W = 0x18;
        inline constexpr std::uintptr_t X = 0x0;
        inline constexpr std::uintptr_t Y = 0x8;
        inline constexpr std::uintptr_t Z = 0x10;
    }

    namespace f_rep_movement {
        inline constexpr std::uintptr_t Acceleration = 0x60;
        inline constexpr std::uintptr_t AngularVelocity = 0x18;
        inline constexpr std::uintptr_t bRepAcceleration = 0x78;
        inline constexpr std::uintptr_t bRepPhysics = 0x78;
        inline constexpr std::uintptr_t bSimulatedPhysicSleep = 0x78;
        inline constexpr std::uintptr_t LinearVelocity = 0x0;
        inline constexpr std::uintptr_t Location = 0x30;
        inline constexpr std::uintptr_t LocationQuantizationLevel = 0x84;
        inline constexpr std::uintptr_t Rotation = 0x48;
        inline constexpr std::uintptr_t RotationQuantizationLevel = 0x86;
        inline constexpr std::uintptr_t ServerFrame = 0x7C;
        inline constexpr std::uintptr_t ServerPhysicsHandle = 0x80;
        inline constexpr std::uintptr_t VelocityQuantizationLevel = 0x85;
    }

    namespace f_rotator {
        inline constexpr std::uintptr_t Pitch = 0x0;
        inline constexpr std::uintptr_t Roll = 0x10;
        inline constexpr std::uintptr_t Yaw = 0x8;
    }

    namespace f_transform {
        inline constexpr std::uintptr_t Rotation = 0x0;
        inline constexpr std::uintptr_t Scale3D = 0x40;
        inline constexpr std::uintptr_t Translation = 0x20;
    }

    namespace f_vector {
        inline constexpr std::uintptr_t X = 0x0;
        inline constexpr std::uintptr_t Y = 0x8;
        inline constexpr std::uintptr_t Z = 0x10;
    }

    namespace f_vector2_d {
        inline constexpr std::uintptr_t X = 0x0;
        inline constexpr std::uintptr_t Y = 0x8;
    }

    namespace f_vector4 {
        inline constexpr std::uintptr_t W = 0x18;
        inline constexpr std::uintptr_t X = 0x0;
        inline constexpr std::uintptr_t Y = 0x8;
        inline constexpr std::uintptr_t Z = 0x10;
    }

    namespace globals {
        inline constexpr std::uintptr_t GEngine = 0x1B245388;
        inline constexpr std::uintptr_t GWorld = 0x1B2439A0;
    }

    namespace structs {
        inline constexpr std::uintptr_t a_actor = [object Object];
        inline constexpr std::uintptr_t a_building_actor = [object Object];
        inline constexpr std::uintptr_t a_building_container = [object Object];
        inline constexpr std::uintptr_t a_building_gameplay_actor = [object Object];
        inline constexpr std::uintptr_t a_building_prop = [object Object];
        inline constexpr std::uintptr_t a_building_sm_actor = [object Object];
        inline constexpr std::uintptr_t a_building_weak_spot = [object Object];
        inline constexpr std::uintptr_t a_camera_actor = [object Object];
        inline constexpr std::uintptr_t a_character = [object Object];
        inline constexpr std::uintptr_t a_controller = [object Object];
        inline constexpr std::uintptr_t a_fort_ai_pawn = [object Object];
        inline constexpr std::uintptr_t a_fort_athena_aircraft = [object Object];
        inline constexpr std::uintptr_t a_fort_athena_supply_drop = [object Object];
        inline constexpr std::uintptr_t a_fort_athena_vehicle = [object Object];
        inline constexpr std::uintptr_t a_fort_game_state = [object Object];
        inline constexpr std::uintptr_t a_fort_game_state_athena = [object Object];
        inline constexpr std::uintptr_t a_fort_inventory = [object Object];
        inline constexpr std::uintptr_t a_fort_pawn = [object Object];
        inline constexpr std::uintptr_t a_fort_physics_pawn = [object Object];
        inline constexpr std::uintptr_t a_fort_pickup = [object Object];
        inline constexpr std::uintptr_t a_fort_player_controller = [object Object];
        inline constexpr std::uintptr_t a_fort_player_controller_athena = [object Object];
        inline constexpr std::uintptr_t a_fort_player_controller_zone = [object Object];
        inline constexpr std::uintptr_t a_fort_player_pawn = [object Object];
        inline constexpr std::uintptr_t a_fort_player_pawn_athena = [object Object];
        inline constexpr std::uintptr_t a_fort_player_state = [object Object];
        inline constexpr std::uintptr_t a_fort_player_state_athena = [object Object];
        inline constexpr std::uintptr_t a_fort_player_state_zone = [object Object];
        inline constexpr std::uintptr_t a_fort_projectile_base = [object Object];
        inline constexpr std::uintptr_t a_fort_safe_zone_indicator = [object Object];
        inline constexpr std::uintptr_t a_fort_weapon = [object Object];
        inline constexpr std::uintptr_t a_fort_weapon_ranged = [object Object];
        inline constexpr std::uintptr_t a_pawn = [object Object];
        inline constexpr std::uintptr_t a_player_camera_manager = [object Object];
        inline constexpr std::uintptr_t a_player_controller = [object Object];
        inline constexpr std::uintptr_t a_player_state = [object Object];
        inline constexpr std::uintptr_t ahud = [object Object];
        inline constexpr std::uintptr_t f_based_movement_info = [object Object];
        inline constexpr std::uintptr_t f_box = [object Object];
        inline constexpr std::uintptr_t f_box_sphere_bounds = [object Object];
        inline constexpr std::uintptr_t f_camera_cache_entry = [object Object];
        inline constexpr std::uintptr_t f_color = [object Object];
        inline constexpr std::uintptr_t f_int_point = [object Object];
        inline constexpr std::uintptr_t f_int_vector = [object Object];
        inline constexpr std::uintptr_t f_linear_color = [object Object];
        inline constexpr std::uintptr_t f_matrix = [object Object];
        inline constexpr std::uintptr_t f_minimal_view_info = [object Object];
        inline constexpr std::uintptr_t f_quat = [object Object];
        inline constexpr std::uintptr_t f_rep_movement = [object Object];
        inline constexpr std::uintptr_t f_rotator = [object Object];
        inline constexpr std::uintptr_t f_transform = [object Object];
        inline constexpr std::uintptr_t f_vector = [object Object];
        inline constexpr std::uintptr_t f_vector2_d = [object Object];
        inline constexpr std::uintptr_t f_vector4 = [object Object];
        inline constexpr std::uintptr_t u_actor_component = [object Object];
        inline constexpr std::uintptr_t u_camera_component = [object Object];
        inline constexpr std::uintptr_t u_capsule_component = [object Object];
        inline constexpr std::uintptr_t u_character_movement_component = [object Object];
        inline constexpr std::uintptr_t u_cheat_manager = [object Object];
        inline constexpr std::uintptr_t u_engine = [object Object];
        inline constexpr std::uintptr_t u_fort_ability_system_component = [object Object];
        inline constexpr std::uintptr_t u_fort_cheat_manager = [object Object];
        inline constexpr std::uintptr_t u_fort_game_viewport_client = [object Object];
        inline constexpr std::uintptr_t u_fort_item = [object Object];
        inline constexpr std::uintptr_t u_fort_movement_comp__character = [object Object];
        inline constexpr std::uintptr_t u_fort_pawn_component = [object Object];
        inline constexpr std::uintptr_t u_game_engine = [object Object];
        inline constexpr std::uintptr_t u_game_instance = [object Object];
        inline constexpr std::uintptr_t u_game_viewport_client = [object Object];
        inline constexpr std::uintptr_t u_input_component = [object Object];
        inline constexpr std::uintptr_t u_level = [object Object];
        inline constexpr std::uintptr_t u_local_player = [object Object];
        inline constexpr std::uintptr_t u_mesh_component = [object Object];
        inline constexpr std::uintptr_t u_movement_component = [object Object];
        inline constexpr std::uintptr_t u_pawn_movement_component = [object Object];
        inline constexpr std::uintptr_t u_player_input = [object Object];
        inline constexpr std::uintptr_t u_primitive_component = [object Object];
        inline constexpr std::uintptr_t u_scene_component = [object Object];
        inline constexpr std::uintptr_t u_skeletal_mesh_component = [object Object];
        inline constexpr std::uintptr_t u_static_mesh_component = [object Object];
        inline constexpr std::uintptr_t u_world = [object Object];
    }

    namespace u_actor_component {
        inline constexpr std::uintptr_t AssetUserData = 0x78;
        inline constexpr std::uintptr_t bAutoActivate = 0x9A;
        inline constexpr std::uintptr_t bCanEverAffectNavigation = 0x9A;
        inline constexpr std::uintptr_t bEditableWhenInherited = 0x9A;
        inline constexpr std::uintptr_t bIsActive = 0x9A;
        inline constexpr std::uintptr_t bIsEditorOnly = 0x9B;
        inline constexpr std::uintptr_t bNetAddressable = 0x98;
        inline constexpr std::uintptr_t bReplicates = 0x98;
        inline constexpr std::uintptr_t bReplicateUsingRegisteredSubObjectList = 0x98;
        inline constexpr std::uintptr_t ComponentTags = 0x68;
        inline constexpr std::uintptr_t CreationMethod = 0xB9;
        inline constexpr std::uintptr_t OnComponentActivated = 0xBA;
        inline constexpr std::uintptr_t OnComponentDeactivated = 0xBB;
        inline constexpr std::uintptr_t PrimaryComponentTick = 0x38;
        inline constexpr std::uintptr_t UCSSerializationIndex = 0x90;
    }

    namespace u_camera_component {
        inline constexpr std::uintptr_t AspectRatio = 0x264;
        inline constexpr std::uintptr_t AspectRatioAxisConstraint = 0x268;
        inline constexpr std::uintptr_t AsymmetricOverscan = 0x270;
        inline constexpr std::uintptr_t AutoPlaneShift = 0x254;
        inline constexpr std::uintptr_t bAutoCalculateOrthoPlanes = 0x250;
        inline constexpr std::uintptr_t bConstrainAspectRatio = 0x269;
        inline constexpr std::uintptr_t bCropOverscan = 0x281;
        inline constexpr std::uintptr_t bEnableFirstPersonFieldOfView = 0x282;
        inline constexpr std::uintptr_t bOverrideAspectRatioAxisConstraint = 0x269;
        inline constexpr std::uintptr_t bScaleResolutionWithOverscan = 0x280;
        inline constexpr std::uintptr_t bUpdateOrthoPlanes = 0x260;
        inline constexpr std::uintptr_t bUseCameraHeightAsViewTarget = 0x261;
        inline constexpr std::uintptr_t bUseFieldOfViewForLOD = 0x269;
        inline constexpr std::uintptr_t FieldOfView = 0x240;
        inline constexpr std::uintptr_t FirstPersonFieldOfView = 0x244;
        inline constexpr std::uintptr_t FirstPersonScale = 0x248;
        inline constexpr std::uintptr_t OrthoFarClipPlane = 0x25C;
        inline constexpr std::uintptr_t OrthoNearClipPlane = 0x258;
        inline constexpr std::uintptr_t OrthoWidth = 0x24C;
        inline constexpr std::uintptr_t Overscan = 0x26C;
    }

    namespace u_capsule_component {
        inline constexpr std::uintptr_t CapsuleHalfHeight = 0x588;
        inline constexpr std::uintptr_t CapsuleRadius = 0x58C;
    }

    namespace u_character_movement_component {
        inline constexpr std::uintptr_t CharacterOwner = 0x198;
        inline constexpr std::uintptr_t CustomMovementMode = 0x232;
        inline constexpr std::uintptr_t GravityDirection = 0x1D8;
        inline constexpr std::uintptr_t GravityScale = 0x1A0;
        inline constexpr std::uintptr_t GravityToWorldTransform = 0x210;
        inline constexpr std::uintptr_t GroundFriction = 0x234;
        inline constexpr std::uintptr_t JumpOffJumpZFactor = 0x1AC;
        inline constexpr std::uintptr_t JumpZVelocity = 0x1A8;
        inline constexpr std::uintptr_t MaxFlySpeed = 0x284;
        inline constexpr std::uintptr_t MaxStepHeight = 0x1A4;
        inline constexpr std::uintptr_t MaxSwimSpeed = 0x280;
        inline constexpr std::uintptr_t MaxWalkSpeed = 0x278;
        inline constexpr std::uintptr_t MaxWalkSpeedCrouched = 0x27C;
        inline constexpr std::uintptr_t MovementMode = 0x231;
        inline constexpr std::uintptr_t NetworkSmoothingMode = 0x233;
        inline constexpr std::uintptr_t OldBaseLocation = 0x260;
        inline constexpr std::uintptr_t OldBaseQuat = 0x240;
        inline constexpr std::uintptr_t WalkableFloorAngle = 0x1CC;
        inline constexpr std::uintptr_t WalkableFloorZ = 0x1D0;
        inline constexpr std::uintptr_t WorldToGravityTransform = 0x1F0;
    }

    namespace u_cheat_manager {
        inline constexpr std::uintptr_t CheatManagerExtensions = 0x78;
        inline constexpr std::uintptr_t DebugCameraControllerClass = 0x30;
        inline constexpr std::uintptr_t DebugCameraControllerRef = 0x28;
    }

    namespace u_engine {
        inline constexpr std::uintptr_t AdditionalFontNames = 0x100;
        inline constexpr std::uintptr_t AdditionalFonts = 0xF0;
        inline constexpr std::uintptr_t ConsoleClass = 0x110;
        inline constexpr std::uintptr_t ConsoleClassName = 0x118;
        inline constexpr std::uintptr_t GameViewportClientClass = 0x130;
        inline constexpr std::uintptr_t GameViewportClientClassName = 0x138;
        inline constexpr std::uintptr_t LargeFont = 0x90;
        inline constexpr std::uintptr_t LargeFontName = 0x98;
        inline constexpr std::uintptr_t LocalPlayerClass = 0x150;
        inline constexpr std::uintptr_t LocalPlayerClassName = 0x158;
        inline constexpr std::uintptr_t MediumFont = 0x70;
        inline constexpr std::uintptr_t MediumFontName = 0x78;
        inline constexpr std::uintptr_t MonospaceFont = 0xD0;
        inline constexpr std::uintptr_t MonospaceFontName = 0xD8;
        inline constexpr std::uintptr_t SmallFont = 0x50;
        inline constexpr std::uintptr_t SmallFontName = 0x58;
        inline constexpr std::uintptr_t SubtitleFont = 0xB0;
        inline constexpr std::uintptr_t SubtitleFontName = 0xB8;
        inline constexpr std::uintptr_t TinyFont = 0x30;
        inline constexpr std::uintptr_t TinyFontName = 0x38;
    }

    namespace u_fort_ability_system_component {
        inline constexpr std::uintptr_t LandingMontagePair = 0xBA8;
        inline constexpr std::uintptr_t LastResolvedEmoteMontage = 0xBD0;
        inline constexpr std::uintptr_t OnClientVehicleBlockingChanged = 0xA68;
        inline constexpr std::uintptr_t RepSharedAnimInfo = 0xBD8;
    }

    namespace u_fort_cheat_manager {
        inline constexpr std::uintptr_t AbilitySystemCycleCounter = 0x9C;
        inline constexpr std::uintptr_t bCanExitWorld = 0x99;
        inline constexpr std::uintptr_t bDebugBeautyMode = 0x98;
        inline constexpr std::uintptr_t bDebugBounceCurve = 0x98;
        inline constexpr std::uintptr_t bDebugInteractTrace = 0x98;
        inline constexpr std::uintptr_t bDebugPickupSpline = 0x98;
        inline constexpr std::uintptr_t bDebugStructuralSupportSystem = 0x98;
        inline constexpr std::uintptr_t bDisplayWindDebugging = 0x98;
        inline constexpr std::uintptr_t bEnableContextMenus = 0x99;
        inline constexpr std::uintptr_t bEnableScoreboard = 0x98;
        inline constexpr std::uintptr_t bForceAILOD = 0x9A;
        inline constexpr std::uintptr_t bFreezeAILOD = 0x9A;
        inline constexpr std::uintptr_t bInfiniteStamina = 0x98;
        inline constexpr std::uintptr_t bShowGameDifficultyHUD = 0x99;
        inline constexpr std::uintptr_t bShowIntensityHUD = 0x99;
        inline constexpr std::uintptr_t bShowItemIDsOnCards = 0x99;
        inline constexpr std::uintptr_t bShowMaxAIHUD = 0x99;
        inline constexpr std::uintptr_t bUnlimitedAIHealth = 0x99;
        inline constexpr std::uintptr_t bUnlimitedHealth = 0x99;
        inline constexpr std::uintptr_t ForcedAILODValue = 0xA0;
    }

    namespace u_fort_game_viewport_client {
        inline constexpr std::uintptr_t NetworkFailureMessage = 0x398;
        inline constexpr std::uintptr_t NetworkFailureMessageAdditionalAnalyticsString = 0x3A8;
    }

    namespace u_fort_item {
        inline constexpr std::uintptr_t OnItemChanged = 0x48;
        inline constexpr std::uintptr_t OnItemDestroyed = 0x70;
    }

    namespace u_fort_movement_comp__character {
        inline constexpr std::uintptr_t AILodRequiredForFloorCheckWhenRendered = 0x10CC;
        inline constexpr std::uintptr_t bIsRidden = 0x10CD;
        inline constexpr std::uintptr_t bMovementProbesEnabled = 0x1058;
        inline constexpr std::uintptr_t bUpdateRotationInVehicle = 0x1120;
        inline constexpr std::uintptr_t ClampMaxSpeedToStreamingSpread = 0x1178;
        inline constexpr std::uintptr_t LandHardSoundFallSpeedThreshold = 0x1088;
        inline constexpr std::uintptr_t LandSoundFallSpeedThreshold = 0x108C;
        inline constexpr std::uintptr_t MovementProbeSetups = 0x1060;
        inline constexpr std::uintptr_t NetworkSmoothingNoThrottleWithinDistanceInMeters = 0x10C4;
        inline constexpr std::uintptr_t NetworkSmoothingThrottleProxyUpdateForPawnLOD = 0x10B0;
        inline constexpr std::uintptr_t NetworkSmoothingViewAngleThreshold = 0x10B4;
        inline constexpr std::uintptr_t NetworkSmoothingViewAngleThresholdSmall = 0x10BC;
        inline constexpr std::uintptr_t NetworkSmoothingVisibilityThreshold = 0x10AC;
        inline constexpr std::uintptr_t OnCharacterLaunchedByPhysicsImpact = 0x1020;
        inline constexpr std::uintptr_t OnInputFilteredByProbe = 0xFE8;
        inline constexpr std::uintptr_t PlayerLodRequiredForFloorCheckWhenRendered = 0x10C8;
        inline constexpr std::uintptr_t PushBumpedPawnClass = 0x1090;
        inline constexpr std::uintptr_t StreamingMaxSpeed = 0x1150;
        inline constexpr std::uintptr_t SurfaceTrackingComponent = 0x1144;
        inline constexpr std::uintptr_t TacticalSprintBrakingTimeThreshold = 0x10D8;
    }

    namespace u_game_engine {
        inline constexpr std::uintptr_t GameInstance = 0x288;
        inline constexpr std::uintptr_t MaxDeltaTime = 0x10F8;
        inline constexpr std::uintptr_t ServerFlushLogInterval = 0x10FC;
    }

    namespace u_game_instance {
        inline constexpr std::uintptr_t LocalPlayers = 0x38;
        inline constexpr std::uintptr_t OnInputDeviceConnectionChange = 0xA0;
        inline constexpr std::uintptr_t OnlineSession = 0x48;
        inline constexpr std::uintptr_t OnPawnControllerChangedDelegates = 0x78;
        inline constexpr std::uintptr_t OnUserInputDevicePairingChange = 0xB0;
        inline constexpr std::uintptr_t ReferencedObjects = 0x50;
    }

    namespace u_game_viewport_client {
        inline constexpr std::uintptr_t DebugProperties = 0x48;
        inline constexpr std::uintptr_t GameInstance = 0x80;
        inline constexpr std::uintptr_t MaxSplitscreenPlayers = 0x68;
        inline constexpr std::uintptr_t ViewportConsole = 0x40;
        inline constexpr std::uintptr_t World = 0x78;
    }

    namespace u_input_component {
        inline constexpr std::uintptr_t CachedKeyToActionInfo = 0x130;
    }

    namespace u_level {
        inline constexpr std::uintptr_t ActorCluster = 0x90;
        inline constexpr std::uintptr_t bIsLightingScenario = 0x258;
        inline constexpr std::uintptr_t LevelBuildDataId = 0x228;
        inline constexpr std::uintptr_t LevelScriptActor = 0xA0;
        inline constexpr std::uintptr_t LightBuildLevelOffset = 0x240;
        inline constexpr std::uintptr_t LightmapTotalSize = 0xC8;
        inline constexpr std::uintptr_t MapBuildData = 0x238;
        inline constexpr std::uintptr_t Model = 0x78;
        inline constexpr std::uintptr_t ModelComponents = 0x80;
        inline constexpr std::uintptr_t NavDataChunks = 0xB8;
        inline constexpr std::uintptr_t NavListEnd = 0xB0;
        inline constexpr std::uintptr_t NavListStart = 0xA8;
        inline constexpr std::uintptr_t NumTextureStreamingDirtyResources = 0x9C;
        inline constexpr std::uintptr_t NumTextureStreamingUnbuiltComponents = 0x98;
        inline constexpr std::uintptr_t OwningWorld = 0x70;
        inline constexpr std::uintptr_t PackedTextureStreamingQualityLevelFeatureLevel = 0x100;
        inline constexpr std::uintptr_t ShadowmapTotalSize = 0xCC;
        inline constexpr std::uintptr_t StaticNavigableGeometry = 0xD0;
        inline constexpr std::uintptr_t StreamingTextureGuids = 0xE0;
        inline constexpr std::uintptr_t StreamingTextures = 0xF0;
    }

    namespace u_local_player {
        inline constexpr std::uintptr_t AspectRatioAxisConstraint = 0xB8;
        inline constexpr std::uintptr_t bSentSplitJoin = 0xC8;
        inline constexpr std::uintptr_t ControllerId = 0xE8;
        inline constexpr std::uintptr_t PendingLevelPlayerControllerClass = 0xC0;
        inline constexpr std::uintptr_t ViewportClient = 0x78;
        inline constexpr std::uintptr_t ViewportClientOverride = 0xE0;
    }

    namespace u_mesh_component {
        inline constexpr std::uintptr_t bEnableMaterialParameterCaching = 0x598;
        inline constexpr std::uintptr_t MaterialSlotsOverlayMaterial = 0x588;
        inline constexpr std::uintptr_t OverlayMaterial = 0x578;
        inline constexpr std::uintptr_t OverlayMaterialMaxDrawDistance = 0x580;
        inline constexpr std::uintptr_t OverrideMaterials = 0x568;
    }

    namespace u_movement_component {
        inline constexpr std::uintptr_t bAutoRegisterPhysicsVolumeUpdates = 0x120;
        inline constexpr std::uintptr_t bAutoRegisterUpdatedComponent = 0x120;
        inline constexpr std::uintptr_t bAutoUpdateTickRegistration = 0x120;
        inline constexpr std::uintptr_t bComponentShouldUpdatePhysicsVolume = 0x120;
        inline constexpr std::uintptr_t bConstrainToPlane = 0x120;
        inline constexpr std::uintptr_t bSnapToPlaneAtStart = 0x120;
        inline constexpr std::uintptr_t bTickBeforeOwner = 0x120;
        inline constexpr std::uintptr_t bUpdateOnlyIfRendered = 0x120;
        inline constexpr std::uintptr_t PlaneConstraintAxisSetting = 0x123;
        inline constexpr std::uintptr_t PlaneConstraintNormal = 0xF0;
        inline constexpr std::uintptr_t PlaneConstraintOrigin = 0x108;
        inline constexpr std::uintptr_t UpdatedComponent = 0xC0;
        inline constexpr std::uintptr_t UpdatedPrimitive = 0xC8;
        inline constexpr std::uintptr_t Velocity = 0xD8;
    }

    namespace u_pawn_movement_component {
        inline constexpr std::uintptr_t PawnOwner = 0x180;
    }

    namespace u_player_input {
        inline constexpr std::uintptr_t DebugExecBindings = 0x160;
        inline constexpr std::uintptr_t InvertedAxis = 0x1A0;
    }

    namespace u_primitive_component {
        inline constexpr std::uintptr_t bAllowCullDistanceVolume = 0x28B;
        inline constexpr std::uintptr_t bAlwaysCreatePhysicsState = 0x28A;
        inline constexpr std::uintptr_t bEnableAutoLODGeneration = 0x28A;
        inline constexpr std::uintptr_t bGenerateOverlapEvents = 0x28A;
        inline constexpr std::uintptr_t bIsActorTextureStreamingBuiltData = 0x28A;
        inline constexpr std::uintptr_t bIsValidTextureStreamingBuiltData = 0x28A;
        inline constexpr std::uintptr_t bMultiBodyOverlap = 0x28A;
        inline constexpr std::uintptr_t bNeverDistanceCull = 0x28A;
        inline constexpr std::uintptr_t bReturnMaterialOnMove = 0x28B;
        inline constexpr std::uintptr_t bTraceComplexOnMove = 0x28B;
        inline constexpr std::uintptr_t bUseViewOwnerDepthPriorityGroup = 0x28B;
        inline constexpr std::uintptr_t CachedMaxDrawDistance = 0x280;
        inline constexpr std::uintptr_t DepthPriorityGroup = 0x284;
        inline constexpr std::uintptr_t HLODBatchingPolicy = 0x288;
        inline constexpr std::uintptr_t IndirectLightingCacheQuality = 0x286;
        inline constexpr std::uintptr_t LDMaxDrawDistance = 0x27C;
        inline constexpr std::uintptr_t LightmapType = 0x287;
        inline constexpr std::uintptr_t MinDrawDistance = 0x278;
        inline constexpr std::uintptr_t ShadowCacheInvalidationBehavior = 0x289;
        inline constexpr std::uintptr_t ViewOwnerDepthPriorityGroup = 0x285;
    }

    namespace u_scene_component {
        inline constexpr std::uintptr_t AttachChildren = 0xE0;
        inline constexpr std::uintptr_t AttachParent = 0xD0;
        inline constexpr std::uintptr_t AttachSocketName = 0xD8;
        inline constexpr std::uintptr_t bAbsoluteLocation = 0x1A0;
        inline constexpr std::uintptr_t bAbsoluteRotation = 0x1A0;
        inline constexpr std::uintptr_t bAbsoluteScale = 0x1A0;
        inline constexpr std::uintptr_t bBoundsChangeTriggersStreamingDataRebuild = 0x1A1;
        inline constexpr std::uintptr_t bComponentToWorldUpdated = 0x1A0;
        inline constexpr std::uintptr_t bComputeBoundsOnceForGame = 0x1A1;
        inline constexpr std::uintptr_t bComputeFastLocalBounds = 0x1A1;
        inline constexpr std::uintptr_t bHiddenInGame = 0x1A1;
        inline constexpr std::uintptr_t bShouldBeAttached = 0x1A0;
        inline constexpr std::uintptr_t bShouldSnapLocationWhenAttached = 0x1A0;
        inline constexpr std::uintptr_t bVisible = 0x1A0;
        inline constexpr std::uintptr_t ClientAttachedChildren = 0xF0;
        inline constexpr std::uintptr_t ComponentVelocity = 0x188;
        inline constexpr std::uintptr_t PhysicsVolume = 0xC8;
        inline constexpr std::uintptr_t RelativeLocation = 0x140;
        inline constexpr std::uintptr_t RelativeRotation = 0x158;
        inline constexpr std::uintptr_t RelativeScale3D = 0x170;
    }

    namespace u_skeletal_mesh_component {
        inline constexpr std::uintptr_t AnimationData = 0x920;
        inline constexpr std::uintptr_t AnimationMode = 0xA17;
        inline constexpr std::uintptr_t AnimClass = 0x900;
        inline constexpr std::uintptr_t AnimScriptInstance = 0x908;
        inline constexpr std::uintptr_t bBlendPhysics = 0xA19;
        inline constexpr std::uintptr_t bDisablePostProcessBlueprint = 0xA19;
        inline constexpr std::uintptr_t bEnablePhysicsOnDedicatedServer = 0xA19;
        inline constexpr std::uintptr_t bHasValidBodies = 0xA19;
        inline constexpr std::uintptr_t bUpdateMeshWhenKinematic = 0xA19;
        inline constexpr std::uintptr_t CachedBoneSpaceTransforms = 0x9A0;
        inline constexpr std::uintptr_t CachedComponentSpaceTransforms = 0x9B0;
        inline constexpr std::uintptr_t ClothTeleportMode = 0xA16;
        inline constexpr std::uintptr_t GlobalAnimRateScale = 0xA10;
        inline constexpr std::uintptr_t KinematicBonesUpdateType = 0xA14;
        inline constexpr std::uintptr_t LineCheckBoundsScale = 0x950;
        inline constexpr std::uintptr_t LinkedInstances = 0x990;
        inline constexpr std::uintptr_t OverridePostProcessAnimBP = 0x910;
        inline constexpr std::uintptr_t PhysicsTransformUpdateMode = 0xA15;
        inline constexpr std::uintptr_t PostProcessAnimInstance = 0x918;
        inline constexpr std::uintptr_t RootBoneTranslation = 0x938;
    }

    namespace u_static_mesh_component {
        inline constexpr std::uintptr_t bCastDistanceFieldIndirectShadow = 0x5E6;
        inline constexpr std::uintptr_t bDisallowMeshPaintPerInstance = 0x5E5;
        inline constexpr std::uintptr_t bDisallowNanite = 0x5E4;
        inline constexpr std::uintptr_t bEvaluateWorldPositionOffset = 0x5E4;
        inline constexpr std::uintptr_t bEvaluateWorldPositionOffsetInRayTracing = 0x5E4;
        inline constexpr std::uintptr_t bForceDisableNanite = 0x5E4;
        inline constexpr std::uintptr_t bForceNaniteForMasked = 0x5E4;
        inline constexpr std::uintptr_t bForceNavigationObstacle = 0x5E5;
        inline constexpr std::uintptr_t bIgnoreInstanceForTextureStreaming = 0x5E5;
        inline constexpr std::uintptr_t bOverrideLightMapRes = 0x5E5;
        inline constexpr std::uintptr_t bOverrideMinLOD = 0x5E5;
        inline constexpr std::uintptr_t bOverrideNavigationExport = 0x5E5;
        inline constexpr std::uintptr_t bOverrideWireframeColor = 0x5E5;
        inline constexpr std::uintptr_t bWorldPositionOffsetWritesVelocity = 0x5E4;
        inline constexpr std::uintptr_t ForcedLodModel = 0x5C8;
        inline constexpr std::uintptr_t MinLOD = 0x5CC;
        inline constexpr std::uintptr_t StaticMesh = 0x5D8;
        inline constexpr std::uintptr_t SubDivisionStepSize = 0x5D0;
        inline constexpr std::uintptr_t WireframeColorOverride = 0x5D4;
        inline constexpr std::uintptr_t WorldPositionOffsetDisableDistance = 0x5E0;
    }

    namespace u_world {
        inline constexpr std::uintptr_t DefaultPhysicsVolume = 0x168;
        inline constexpr std::uintptr_t DemoNetDriver = 0x158;
        inline constexpr std::uintptr_t ExtraReferencedObjects = 0x78;
        inline constexpr std::uintptr_t ForegroundLineBatcher = 0x58;
        inline constexpr std::uintptr_t LineBatcher = 0x48;
        inline constexpr std::uintptr_t LineBatchers = 0x108;
        inline constexpr std::uintptr_t MakingInvisibleLevels = 0x148;
        inline constexpr std::uintptr_t MakingVisibleLevels = 0x138;
        inline constexpr std::uintptr_t MyParticleEventManager = 0x160;
        inline constexpr std::uintptr_t NetDriver = 0x40;
        inline constexpr std::uintptr_t NetworkManager = 0x60;
        inline constexpr std::uintptr_t PerModuleDataObjects = 0x88;
        inline constexpr std::uintptr_t PersistentLevel = 0x38;
        inline constexpr std::uintptr_t PersistentLineBatcher = 0x50;
        inline constexpr std::uintptr_t PhysicsCollisionHandler = 0x68;
        inline constexpr std::uintptr_t PhysicsQueryHandler = 0x70;
        inline constexpr std::uintptr_t ServerStreamingLevelsVisibility = 0xE0;
        inline constexpr std::uintptr_t StreamingLevels = 0xA8;
        inline constexpr std::uintptr_t StreamingLevelsPrefix = 0xE8;
        inline constexpr std::uintptr_t StreamingLevelsToConsider = 0xB8;
    }

} // namespace off
