#!/usr/bin/env node
// Regenerate airfn/offsets/offsets.h from cheatoffsets.com.
// ETag-conditional GET — no-op if the upstream hasn't published a new dump.
//
// Run:   node scripts/gen_offsets.mjs
// CI:    scheduled every 30 min (see .github/workflows/offsets.yml)
//
// Owner: viru.

import { readFile, writeFile, mkdir } from "node:fs/promises";
import { existsSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname   = dirname(fileURLToPath(import.meta.url));
const ROOT        = join(__dirname, "..");
const OUT_HEADER  = join(ROOT, "airfn", "offsets", "offsets.h");
const ETAG_CACHE  = join(ROOT, "airfn", "offsets", ".etag");
const API_URL     = "https://www.cheatoffsets.com/api/games/fortnite/current";

// ---------- Markdown parser (mirrors airfn-web/lib/offsets.ts) --------------
function parseMarkdown(md) {
    const tree = {};
    const blocks = [...md.matchAll(/```cpp\r?\n([\s\S]*?)```/g)].map(m => m[1]);
    const fieldRe = /^\s*inline\s+(?:static\s+)?constexpr\s+\w[\w:\s]*\s+(\w+)\s*=\s*(0x[0-9a-fA-F]+|-?\d+)\s*;/;
    const structOpenRe = /^\s*struct\s+(\w+)\s*[:{]/;
    const structCloseRe = /^\s*};/;
    for (const block of blocks) {
        let cur = null;
        for (const raw of block.split(/\r?\n/)) {
            const so = raw.match(structOpenRe);
            if (so) { cur = so[1]; continue; }
            if (structCloseRe.test(raw)) { cur = null; continue; }
            const f = raw.match(fieldRe);
            if (!f) continue;
            const [, name, value] = f;
            const bucket = cur ?? "globals";
            tree[bucket] ??= {};
            if (tree[bucket][name] === undefined) tree[bucket][name] = value;
        }
    }
    return tree;
}

// ---------- Emit header -----------------------------------------------------
function emitHeader(payload, tree) {
    const iso = new Date().toISOString();
    const lines = [];
    lines.push("// AUTO-GENERATED by scripts/gen_offsets.mjs — DO NOT EDIT.");
    lines.push("// Rerun `node scripts/gen_offsets.mjs` to refresh.");
    lines.push(`// Last refresh: ${iso}`);
    lines.push(`// Build id:     ${payload.id}`);
    lines.push(`// Game version: ${payload.version} (${payload.label})`);
    lines.push("");
    lines.push("#pragma once");
    lines.push("#include <cstdint>");
    lines.push("");
    lines.push("namespace off {");
    lines.push("");
    lines.push(`    inline constexpr const char* build_version = "${payload.version}";`);
    lines.push(`    inline constexpr const char* build_label   = "${payload.label}";`);
    lines.push(`    inline constexpr std::uint64_t build_id    = ${payload.id}ULL;`);
    lines.push("");

    const names = Object.keys(tree).sort();
    for (const bucket of names) {
        lines.push(`    namespace ${bucket} {`);
        const fields = Object.entries(tree[bucket]).sort(([a],[b]) => a.localeCompare(b));
        for (const [name, value] of fields) {
            lines.push(`        inline constexpr std::uintptr_t ${name} = ${value};`);
        }
        lines.push(`    }`);
        lines.push("");
    }
    lines.push("} // namespace off");
    lines.push("");
    return lines.join("\n");
}

// ---------- ETag cache ------------------------------------------------------
async function loadEtag() {
    if (!existsSync(ETAG_CACHE)) return null;
    try { return (await readFile(ETAG_CACHE, "utf8")).trim() || null; } catch { return null; }
}
async function saveEtag(etag) {
    if (!etag) return;
    await mkdir(dirname(ETAG_CACHE), { recursive: true });
    await writeFile(ETAG_CACHE, etag);
}

// ---------- Main ------------------------------------------------------------
async function main() {
    const prev = await loadEtag();
    const headers = { "User-Agent": "airfn-gen-offsets/1" };
    if (prev) headers["If-None-Match"] = prev;

    const res = await fetch(API_URL, { headers });
    if (res.status === 304) {
        console.log("[gen_offsets] 304 — upstream unchanged. header left as-is.");
        return;
    }
    if (!res.ok) {
        console.error(`[gen_offsets] upstream ${res.status}`);
        process.exit(1);
    }

    const payload = await res.json();
    const countFields = (t) => t ? Object.values(t).reduce((a, b) => a + (b && typeof b === "object" ? Object.keys(b).length : 0), 0) : 0;
    const apiCount = countFields(payload.offsets);
    const parsedTree = parseMarkdown(payload.markdown || "");
    const parsedCount = countFields(parsedTree);

    let apiTree;
    if (apiCount === 0 && parsedCount > 0) {
        apiTree = parsedTree;
        console.log(`[gen_offsets] api tree empty, using markdown parse (${parsedCount} fields)`);
    } else if (apiCount > 0) {
        apiTree = { ...parsedTree, ...payload.offsets }; // api authoritative
        console.log(`[gen_offsets] merged api(${apiCount}) + parsed(${parsedCount})`);
    } else {
        console.error("[gen_offsets] both api tree and markdown parse are empty. abort.");
        process.exit(1);
    }

    const header = emitHeader(payload, apiTree);
    await mkdir(dirname(OUT_HEADER), { recursive: true });
    await writeFile(OUT_HEADER, header);
    await saveEtag(res.headers.get("etag"));

    const totalFields = Object.values(apiTree).reduce((a, b) => a + Object.keys(b).length, 0);
    console.log(`[gen_offsets] wrote ${OUT_HEADER}`);
    console.log(`[gen_offsets] build=${payload.version} id=${payload.id} fields=${totalFields}`);
}

main().catch(err => { console.error(err); process.exit(1); });
